// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: firebase/v1/firebase.proto

package firebasev1connect

import (
	v1 "OlympusGCP-Firebase/40000-Communication-Contracts/430-Protocol-Definitions/000-gen/firebase/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FirebaseServiceName is the fully-qualified name of the FirebaseService service.
	FirebaseServiceName = "firebase.v1.FirebaseService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FirebaseServiceCreateUserProcedure is the fully-qualified name of the FirebaseService's
	// CreateUser RPC.
	FirebaseServiceCreateUserProcedure = "/firebase.v1.FirebaseService/CreateUser"
	// FirebaseServiceSetDocumentProcedure is the fully-qualified name of the FirebaseService's
	// SetDocument RPC.
	FirebaseServiceSetDocumentProcedure = "/firebase.v1.FirebaseService/SetDocument"
)

// FirebaseServiceClient is a client for the firebase.v1.FirebaseService service.
type FirebaseServiceClient interface {
	CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error)
	SetDocument(context.Context, *connect.Request[v1.SetDocumentRequest]) (*connect.Response[v1.SetDocumentResponse], error)
}

// NewFirebaseServiceClient constructs a client for the firebase.v1.FirebaseService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFirebaseServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FirebaseServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	firebaseServiceMethods := v1.File_firebase_v1_firebase_proto.Services().ByName("FirebaseService").Methods()
	return &firebaseServiceClient{
		createUser: connect.NewClient[v1.CreateUserRequest, v1.CreateUserResponse](
			httpClient,
			baseURL+FirebaseServiceCreateUserProcedure,
			connect.WithSchema(firebaseServiceMethods.ByName("CreateUser")),
			connect.WithClientOptions(opts...),
		),
		setDocument: connect.NewClient[v1.SetDocumentRequest, v1.SetDocumentResponse](
			httpClient,
			baseURL+FirebaseServiceSetDocumentProcedure,
			connect.WithSchema(firebaseServiceMethods.ByName("SetDocument")),
			connect.WithClientOptions(opts...),
		),
	}
}

// firebaseServiceClient implements FirebaseServiceClient.
type firebaseServiceClient struct {
	createUser  *connect.Client[v1.CreateUserRequest, v1.CreateUserResponse]
	setDocument *connect.Client[v1.SetDocumentRequest, v1.SetDocumentResponse]
}

// CreateUser calls firebase.v1.FirebaseService.CreateUser.
func (c *firebaseServiceClient) CreateUser(ctx context.Context, req *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	return c.createUser.CallUnary(ctx, req)
}

// SetDocument calls firebase.v1.FirebaseService.SetDocument.
func (c *firebaseServiceClient) SetDocument(ctx context.Context, req *connect.Request[v1.SetDocumentRequest]) (*connect.Response[v1.SetDocumentResponse], error) {
	return c.setDocument.CallUnary(ctx, req)
}

// FirebaseServiceHandler is an implementation of the firebase.v1.FirebaseService service.
type FirebaseServiceHandler interface {
	CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error)
	SetDocument(context.Context, *connect.Request[v1.SetDocumentRequest]) (*connect.Response[v1.SetDocumentResponse], error)
}

// NewFirebaseServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFirebaseServiceHandler(svc FirebaseServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	firebaseServiceMethods := v1.File_firebase_v1_firebase_proto.Services().ByName("FirebaseService").Methods()
	firebaseServiceCreateUserHandler := connect.NewUnaryHandler(
		FirebaseServiceCreateUserProcedure,
		svc.CreateUser,
		connect.WithSchema(firebaseServiceMethods.ByName("CreateUser")),
		connect.WithHandlerOptions(opts...),
	)
	firebaseServiceSetDocumentHandler := connect.NewUnaryHandler(
		FirebaseServiceSetDocumentProcedure,
		svc.SetDocument,
		connect.WithSchema(firebaseServiceMethods.ByName("SetDocument")),
		connect.WithHandlerOptions(opts...),
	)
	return "/firebase.v1.FirebaseService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FirebaseServiceCreateUserProcedure:
			firebaseServiceCreateUserHandler.ServeHTTP(w, r)
		case FirebaseServiceSetDocumentProcedure:
			firebaseServiceSetDocumentHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFirebaseServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFirebaseServiceHandler struct{}

func (UnimplementedFirebaseServiceHandler) CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("firebase.v1.FirebaseService.CreateUser is not implemented"))
}

func (UnimplementedFirebaseServiceHandler) SetDocument(context.Context, *connect.Request[v1.SetDocumentRequest]) (*connect.Response[v1.SetDocumentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("firebase.v1.FirebaseService.SetDocument is not implemented"))
}
